// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'green': string;
  'normalSize': string;
  'normalWidth': string;
  'root': string;
  'small': string;
  'wide': string;
  'yellow': string;
}
export const cssExports: CssExports;
export default cssExports;
