// This file is automatically generated.
// Please do not change this file!
interface CssExports {
  'container': string;
  'logo': string;
  'menu': string;
  'menuElement': string;
  'menuLink': string;
}
export const cssExports: CssExports;
export default cssExports;
